<?php






                    // echo "Mamy tu elementów: ".$lines_numberOfElements."<br><br>";
                    // echo "Mamy tu elementów klucz-wartość: ".$lines_numberOfElements_keyValuePairs."<br><br>";

                  

                    
                    //echo '<pre>'.print_r(get_class_methods($reflect), true).'</pre>';
                    
                    
                    // $tempArray = (array) $this->objOrder->lines;
                    
                    // echo "<pre>";
                    // print_r($tempArray);
                    // echo "</pre>";

                    // foreach ($tempArray as $key => $value)
                    // {
                    //     echo "<br><br>";
                    //     echo "Nazwa klucza: ".$key." wartość: ".$value."<br>";
                    //     echo "Typ klucza: ".gettype($key)." Typ wartości: ".gettype($value)."<br>";
                    //     echo "<br><br>";
                    // }




                    // foreach ($tempArray as $element)
                    // {

                    //     echo "Typ elementu: ".gettype($element)."<br><br>";
                    //     //echo "<br><br>".var_dump($this->objOrder->lines)." Key name: ".key($this->objOrder->lines)."<br><br>";
                    // }
                    

                    
                    
                    // // NIE DZIAŁA:
                    // foreach ($this->objOrder->lines as $element)
                    // {
                    //     // NAZWA KLUCZA TO NAZWA KLUCZA
                    //     // JEGO WARTOŚĆ TO INTEGER!!!
                    //     echo "Typ elementu: ".gettype($element)."<br><br>";
                    //     //echo "<br><br>".var_dump($this->objOrder->lines)." Key name: ".key($this->objOrder->lines)."<br><br>";
                    // }
                    
                    



                    //echo key($this->objOrder->lines);


                // $niewiadomoco = (array) $this->objOrder->lines;
                // $niewiadomoco["Kutno-Warszawa"] = 10000;
                // echo "Typ <b>niewiadomoco</b> to: ".gettype($niewiadomoco)."<br><br>";
                // //echo "Typ <b>Kutno-Warszawa</b> to: ".gettype($niewiadomoco[0])."<br><br>";
                   
                // echo "<pre>";
                // print_r($niewiadomoco);
                // echo "</pre>";


                    // foreach ($this->objOrder->lines as $key => $value)
                    // {
                    //     echo "Para:   $key => $value<br>";
                    // }



             //echo "Typ <b>Kutno-Warszawa</b> to: ".gettype($this->objOrder->lines)."<br><br>";
                    

            // var_dump($this->objOrder);

            // echo "<br><br>:";
            // echo "Czy obiekt jest pusty: ".(int) empty($this->objOrder);
         

            // $piesek = new stdClass();
            // $piesek->iloscNog = 4;
            // $piesek->ileGlow = 1;
            // $piesek->imiona = array("Aleks", "Reksio", "Rad");
            // $piesek->wlasciciel = "";

            // if (isset($piesek->ustawione))
            // {
            //     echo "<br><br>USTAWIONE!!!<br><br>";
            // }

            // if (is_null($piesek->wlasciciel))
            // {
            //     echo "<br><br>Właściwość jest nuullem!!!<br><br>";
            // }

            // if (empty($piesek->wlasciciel))
            // {
            //     echo "<br><br>Właściwość pusta!!!<br><br>";
            // }

            // $reflect = new ReflectionObject($this->objOrder);

            
            // echo '<pre>'.print_r(get_class_methods($reflect), true).'</pre>';
            
            // $properties = $reflect->getProperties();

            // echo "<pre>";
            // print_r($properties);
            // echo "</pre>";

            // echo "Ilość pól: ".count($properties);





                    // $KW = new stdClass();
                    // $KW->name = "Kutno-Warszawa";
                    // $KW->distance = 10;

                    // $KL = new stdClass();
                    // $KL->name = "Kutno-Lodz";
                    // $KL->distance = 20;


                    // $this->objOrder->kupa = [];
                    // $this->objOrder->kupa[] = $KW;
                    // $this->objOrder->kupa[] = $KL;

                    // echo "<pre>".print_r($this->objOrder->kupa)."</pre>";              




















?>